#include "../enemy.h"

#define NUM_SCREENS 38
#define MAP_NAME australia
#ifndef SPAWN_ENTRY
#define PASTE4(a, b, c, d) a ## b ## c ## d
#define SPAWN_ENTRY2(mapname, index) PASTE4(spawn_,mapname,_screen,index)
#define SPAWN_ENTRY(index) SPAWN_ENTRY2(MAP_NAME, index)
#define PASTE2(a, b) a ## b
#define SPAWN_MAP1(mapname) PASTE2(spawn_screens_, mapname)
#define SPAWN_MAP SPAWN_MAP1(MAP_NAME)
#endif

static const struct enemy_spawn SPAWN_ENTRY(1)[] = {
	[0] = {
		.scroll_line = 40,
		.weapon = EW_GRENADE,
		.x = 0,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 10,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 25,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 53,
				.vel = 6,
			},
		},
		.shots = {
			[0] =  8,
			[1] =  24,
			[2] =  54,
			[3] =  66,
		},
	},
	[1] = {
		.scroll_line = 40,
		.weapon = EW_GRENADE,
		.x = 161,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_SSW,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 33,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 43,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 9,
			[1] = 32,
			[2] = 43,
			[3] = 0,
		},
	},
	[2] = {
		.scroll_line = 40,
		.weapon = EW_GUN,
		.x = 190,
		.y = 6,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 29,
			[1] = 52,
			[2] = 74,
			[3] = 100,
			[4] = 117,
		},
	},
	[3] = {
		.scroll_line = 52,
		.weapon = EW_GUN,
		.x = 190,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 8,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 20,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 51,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 5,
			[1] = 30,
			[2] = 51,
			[3] = 0,
			[4] = 0,
		},
	},
	[4] = {
		.scroll_line = 100,
		.weapon = EW_GRENADE,
		.x = -14,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 3,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 19,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 19,
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[5] = {
		.scroll_line = 127,
		.weapon = EW_GUN,
		.x = 78,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 23,
			[1] = 66,
			[2] = 90,
			[3] = 0,
			[4] = 0,
		},
	},
	[6] = {
		.scroll_line = 155,
		.weapon = EW_GUN,
		.x = -15,
		.y = 3,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_SO,
				.start_step = 6,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 13,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 49,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 6,
			[1] = 29,
			[2] = 49,
			[3] = 0,
			[4] = 0,
		},
	},
	[7] = {
		.scroll_line = 175,
		.weapon = EW_GUN,
		.x = -13,
		.y = 20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 6,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 27,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 51,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 5,
			[1] = 27,
			[2] = 51,
			[3] = 0,
			[4] = 0,
		},
	},
};

static const struct enemy_spawn SPAWN_ENTRY(2)[] = {
	[0] = {
		.scroll_line = 2,
		.weapon = EW_GUN,
		.x = 190,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WNW,
				.start_step = 28,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_LEFT,
				.dir = DIR16_W,
				.start_step = 54,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 28,
			[1] = 50,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[1] = {
		.scroll_line = 21,
		.weapon = EW_GUN,
		.x = 78,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 26,
			[1] = 68,
			[2] = 89,
			[3] = 0,
			[4] = 0,
		},
	},
	[2] = {
		.scroll_line = 25,
		.weapon = EW_GUN,
		.x = 191,
		.y = 1,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WNW,
				.start_step = 26,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_LEFT,
				.dir = DIR16_W,
				.start_step = 51,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 11,
			[1] = 26,
			[2] = 50,
			[3] = 0,
			[4] = 0,
		},
	},
	[3] = {
		.scroll_line = 60,
		.weapon = EW_GUN,
		.x = -14,
		.y = 18,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 29,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 26,
			[2] = 47,
			[3] = 0,
			[4] = 0,
		},
	},
	[4] = {
		.scroll_line = 73,
		.weapon = EW_GUN,
		.x = 51,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_SSO,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_SSO,
				.start_step = 24,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_SSW,
				.start_step = 48,
				.vel = 6,
			},
			[4] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 74,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 24,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[5] = {
		.scroll_line = 91,
		.weapon = EW_GUN,
		.x = 51,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_SSO,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_SSO,
				.start_step = 24,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_SSW,
				.start_step = 48,
				.vel = 6,
			},
			[4] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 74,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 24,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[6] = {
		.scroll_line = 106,
		.weapon = EW_GUN,
		.x = 12,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_SSO,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 17,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_SSO,
				.start_step = 22,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_SSW,
				.start_step = 48,
				.vel = 6,
			},
			[4] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 73,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 17,
			[1] = 26,
			[2] = 50,
			[3] = 72,
			[4] = 0,
		},
	},
	[7] = {
		.scroll_line = 113,
		.weapon = EW_GUN,
		.x = 190,
		.y = 3,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WNW,
				.start_step = 10,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 24,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 10,
			[1] = 24,
			[2] = 37,
			[3] = 57,
			[4] = 0,
		},
	},
	[8] = {
		.scroll_line = 117,
		.weapon = EW_GUN,
		.x = 191,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 16,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 32,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 16,
			[1] = 30,
			[2] = 49,
			[3] = 0,
			[4] = 0,
		},
	},
	[9] = {
		.scroll_line = 121,
		.weapon = EW_GUN,
		.x = 192,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_LEFT,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 7,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 32,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 50,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 6,
			[1] = 29,
			[2] = 50,
			[3] = 0,
			[4] = 0,
		},
	},
	[10] = {
		.scroll_line = 136,
		.weapon = EW_GUN,
		.x = 190,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WNW,
				.start_step = 10,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 23,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 10,
			[1] = 23,
			[2] = 39,
			[3] = 56,
			[4] = 0,
		},
	},
	[11] = {
		.scroll_line = 136,
		.weapon = EW_GUN,
		.x = 190,
		.y = 6,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WNW,
				.start_step = 11,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 35,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 58,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 11,
			[1] = 35,
			[2] = 58,
			[3] = 0,
			[4] = 0,
		},
	},
	[12] = {
		.scroll_line = 148,
		.weapon = EW_GUN,
		.x = 191,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 17,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 30,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 17,
			[1] = 28,
			[2] = 51,
			[3] = 0,
			[4] = 0,
		},
	},
	[13] = {
		.scroll_line = 157,
		.weapon = EW_GUN,
		.x = 190,
		.y = 1,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_LEFT,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 6,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 34,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 50,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 5,
			[1] = 28,
			[2] = 50,
			[3] = 0,
			[4] = 0,
		},
	},
	[14] = {
		.scroll_line = 166,
		.weapon = EW_GUN,
		.x = 190,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WNW,
				.start_step = 11,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 35,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 58,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 11,
			[1] = 35,
			[2] = 58,
			[3] = 0,
			[4] = 0,
		},
	},
	[15] = {
		.scroll_line = 178,
		.weapon = EW_GUN,
		.x = 17,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 26,
			[1] = 66,
			[2] = 89,
			[3] = 0,
			[4] = 0,
		},
	},
	[16] = {
		.scroll_line = 183,
		.weapon = EW_GUN,
		.x = 81,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 25,
			[1] = 66,
			[2] = 91,
			[3] = 0,
			[4] = 0,
		},
		
	},
	[17] = {
		.scroll_line = 184,
		.weapon = EW_GUN,
		.x = 112,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 25,
			[1] = 66,
			[2] = 91,
			[3] = 0,
			[4] = 0,
		},
	},
	[18] = {
		.scroll_line = 187,
		.weapon = EW_GUN,
		.x = 31,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 23,
			[1] = 64,
			[2] = 86,
			[3] = 0,
			[4] = 0,
		},
	},
	[19] = {
		.scroll_line = 191,
		.weapon = EW_GUN,
		.x = 96,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 23,
			[1] = 61,
			[2] = 85,
			[3] = 0,
			[4] = 0,
		},
	},
};

static const struct enemy_spawn SPAWN_ENTRY(3)[] = {
	[0] = {
		.scroll_line = 4,
		.weapon = EW_GUN,
		.x = 16,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 24,
			[1] = 65,
			[2] = 90,
			[3] = 0,
			[4] = 0,
		},
	},
	[1] = {
		.scroll_line = 8,
		.weapon = EW_GUN,
		.x = 49,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 22,
			[1] = 66,
			[2] = 89,
			[3] = 0,
			[4] = 0,
		},
	},
	[2] = {
		.scroll_line = 10,
		.weapon = EW_GUN,
		.x = 110,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 20,
			[1] = 61,
			[2] = 88,
			[3] = 0,
			[4] = 0,
		},
	},
	[3] = {
		.scroll_line = 17,
		.weapon = EW_GRENADE,
		.x = 190,
		.y = 17,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 10,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_SO,
				.start_step = 22,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 26,
				.vel = 6,
			},
			[4] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 32,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 12,
			[1] = 22,
			[2] = 32,
			[3] = 0,
			[4] = 0,
		},
	},
	[4] = {
		.scroll_line = 21,
		.weapon = EW_GRENADE,
		.x = 191,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 39,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 60,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 39,
			[2] = 60,
			[3] = 0,
			[4] = 0,
		},
	},
	[5] = { 
		/* the following 3 should all start on line 90
		but each one with a little delay */
		.scroll_line = 88,
		.weapon = EW_GUN,
		.x = 48,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 24,
			[1] = 68,
			[2] = 86,
			[3] = 0,
			[4] = 0,
		},
	},
	[6] = {
		.scroll_line = 89,
		.weapon = EW_GUN,
		.x = 80,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 24,
			[1] = 68,
			[2] = 86,
			[3] = 0,
			[4] = 0,
		},
	},
	[7] = {
		.scroll_line = 90,
		.weapon = EW_GUN,
		.x = 112,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 24,
			[1] = 68,
			[2] = 86,
			[3] = 0,
			[4] = 0,
		},
	},
	[8] = {
		.scroll_line = 97,
		.weapon = EW_GUN,
		.x = 64,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 20,
			[1] = 64,
			[2] = 88,
			[3] = 0,
			[4] = 0,
		},
	},
	[9] = {
		.scroll_line = 106,
		.weapon = EW_GUN,
		.x = 16,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 21,
			[1] = 67,
			[2] = 86,
			[3] = 0,
			[4] = 0,
		},
	},
	[10] = {
		.scroll_line = 107, 
		/* should actually be started at 106 like his companion above
		 * but with one frame delay */
		.weapon = EW_GUN,
		.x = 48,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 21,
			[1] = 67,
			[2] = 86,
			[3] = 0,
			[4] = 0,
		},
	},
	[11] = {
		.scroll_line = 109,
		.weapon = EW_GUN,
		.x = 80,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 22,
			[1] = 67,
			[2] = 86,
			[3] = 0,
			[4] = 0,
		},
	},
	[12] = {
		.scroll_line = 115,
		.weapon = EW_GRENADE,
		.x = 191,
		.y = 20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 9,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 23,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 34,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 9,
			[1] = 23,
			[2] = 34,
			[3] = 0,
			[4] = 0,
		},
	},
	[13] = {
		.scroll_line = 115,
		.weapon = EW_GRENADE,
		.x = 191,
		.y = 3,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 40,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 62,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 40,
			[2] = 62,
			[3] = 0,
			[4] = 0,
		},
	},
	[14] = {
		.scroll_line = 140,
		.weapon = EW_GUN,
		.x = -15,
		.y = 4,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_ONO,
				.start_step = 27,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 49,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 10,
			[1] = 27,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[15] = {
		.scroll_line = 151,
		.weapon = EW_GRENADE,
		.x = 191,
		.y = 4,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WNW,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 38,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_LEFT,
				.dir = DIR16_W,
				.start_step = 40,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 38,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[16] = {
		.scroll_line = 151,
		.weapon = EW_GUN,
		.x = 190,
		.y = 5,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 28,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 28,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[17] = {
		.scroll_line = 156,
		.weapon = EW_GUN,
		.x = -14,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_ONO,
				.start_step = 26,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 53,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 10,
			[1] = 26,
			[2] = 50,
			[3] = 0,
			[4] = 0,
		},
	},
	[18] = {
		.scroll_line = 178,
		.weapon = EW_GUN,
		.x = -15,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 29,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 29,
			[2] = 47,
			[3] = 0,
			[4] = 0,
		},
	},
	[19] = {
		.scroll_line = 186,
		.weapon = EW_GUN,
		.x = 191,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 16,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 27,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 16,
			[1] = 27,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
};

static const struct enemy_spawn SPAWN_ENTRY(4)[] = {
	[0] = {
		.scroll_line = 0,
		.weapon = EW_GRENADE,
		.x = 190,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WNW,
				.start_step = 16,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_LEFT,
				.dir = DIR16_W,
				.start_step = 37,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 16,
			[1] = 35,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[1] = {
		.scroll_line = 10,
		.weapon = EW_GUN,
		.x = -15,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 11,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_ONO,
				.start_step = 32,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 53,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 11,
			[1] = 32,
			[2] = 50,
			[3] = 0,
			[4] = 0,
		},
	},
	[2] = {
		.scroll_line = 15,
		.weapon = EW_GRENADE,
		.x = -14,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_ONO,
				.start_step = 16,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_RIGHT,
				.dir = DIR16_O,
				.start_step = 43,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 16,
			[1] = 41,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[3] = {
		.scroll_line = 28,
		.weapon = EW_GUN,
		.x = 191,
		.y = 4,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 16,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 28,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 16,
			[1] = 28,
			[2] = 50,
			[3] = 0,
			[4] = 0,
		},
	},
	[4] = {
		.scroll_line = 35,
		.weapon = EW_GRENADE,
		.x = 190,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WNW,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_LEFT,
				.dir = DIR16_W,
				.start_step = 40,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 38,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[5] = {
		.scroll_line = 39,
		.weapon = EW_GUN,
		.x = -14,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 9,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 33,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 51,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 8,
			[1] = 29,
			[2] = 51,
			[3] = 0,
			[4] = 0,
		},
	},
	[6] = {
		.scroll_line = 52,
		.weapon = EW_GUN,
		.x = -14,
		.y = 21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 9,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 33,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 48,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 8,
			[1] = 33,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[7] = {
		.scroll_line = 57,
		.weapon = EW_GUN,
		.x = -14,
		.y = 4,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 9,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 31,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 50,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 8,
			[1] = 31,
			[2] = 50,
			[3] = 0,
			[4] = 0,
		},
	},
	[8] = {
		.scroll_line = 82,
		.weapon = EW_GRENADE,
		.x = 190,
		.y = 6,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 16,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 40,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 64,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 16,
			[1] = 40,
			[2] = 64,
			[3] = 0,
			[4] = 0,
		},
	},
	[9] = {
		.scroll_line = 86,
		.weapon = EW_GRENADE,
		.x = 190,
		.y = 1,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 10,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 23,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 34,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 10,
			[1] = 23,
			[2] = 34,
			[3] = 0,
			[4] = 0,
		},
	},
	[10] = {
		.scroll_line = 98,
		.weapon = EW_GRENADE,
		.x = 190,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 16,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 37,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 57,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 16,
			[1] = 37,
			[2] = 57,
			[3] = 0,
			[4] = 0,
		},
	},
	[11] = {
		.scroll_line = 118,
		.weapon = EW_GRENADE,
		.x = 191,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 38,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 60,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 38,
			[2] = 60,
			[3] = 0,
			[4] = 0,
		},
	},
	[12] = {
		.scroll_line = 127,
		.weapon = EW_GRENADE,
		.x = 191,
		.y = 1,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 11,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 23,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 36,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 11,
			[1] = 23,
			[2] = 36,
			[3] = 0,
			[4] = 0,
		},
	},
	[13] = {
		.scroll_line = 136,
		.weapon = EW_GRENADE,
		.x = 190,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 39,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 62,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 39,
			[2] = 62,
			[3] = 0,
			[4] = 0,
		},
	},
	[14] = {
		.scroll_line = 161,
		.weapon = EW_GUN,
		.x = 52,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 18,
			[1] = 62,
			[2] = 83,
			[3] = 0,
			[4] = 0,
		},
	},
	[15] = {
		.scroll_line = 164,
		.weapon = EW_GUN,
		.x = 96,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 22,
			[1] = 65,
			[2] = 87,
			[3] = 0,
			[4] = 0,
		},
	},
	[16] = {
		.scroll_line = 167,
		.weapon = EW_GUN,
		.x = 127,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 24,
			[1] = 66,
			[2] = 87,
			[3] = 0,
			[4] = 0,
		},
	},
	[17] = {
		.scroll_line = 187,
		.weapon = EW_GRENADE,
		.x = 191,
		.y = 1,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 39,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 62,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 39,
			[2] = 62,
			[3] = 0,
			[4] = 0,
		},
	},
};

static const struct enemy_spawn SPAWN_ENTRY(5)[] = {
	[0] = {
		.scroll_line = 4,
		.weapon = EW_GRENADE,
		.x = 190,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 11,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 22,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 32,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 11,
			[1] = 22,
			[2] = 32,
			[3] = 0,
			[4] = 0,
		},
	},
	[1] = {
		.scroll_line = 15,
		.weapon = EW_GRENADE,
		.x = 191,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_WSW,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 41,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 65,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 41,
			[2] = 65,
			[3] = 0,
			[4] = 0,
		},
	},
	[2] = {
		.scroll_line = 25,
		.weapon = EW_GUN,
		.x = -14,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 28,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 28,
			[2] = 49,
			[3] = 0,
			[4] = 0,
		},
	},
	[3] = {
		.scroll_line = 34,
		.weapon = EW_GUN,
		.x = -15,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 7,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 28,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 48,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 6,
			[1] = 28,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[4] = {
		.scroll_line = 41,
		.weapon = EW_GUN,
		.x = -15,
		.y = 16,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 17,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 27,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 17,
			[1] = 27,
			[2] = 51,
			[3] = 0,
			[4] = 0,
		},
	},
	[5] = {
		.scroll_line = 53,
		.weapon = EW_GUN,
		.x = -15,
		.y = 20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 7,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 29,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 50,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 6,
			[1] = 29,
			[2] = 50,
			[3] = 0,
			[4] = 0,
		},
	},
	[6] = {
		.scroll_line = 65,
		.weapon = EW_GUN,
		.x = -14,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 28,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 28,
			[2] = 47,
			[3] = 0,
			[4] = 0,
		},
	},
	[7] = {
		.scroll_line = 73,
		.weapon = EW_GUN,
		.x = -14,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 6,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 17,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 48,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 6,
			[1] = 28,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[8] = {
		.scroll_line = 85,
		.weapon = EW_GUN,
		.x = -14,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_O,
				.start_step = 17,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER2_DOWN,
				.dir = DIR16_OSO,
				.start_step = 48,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 6,
			[1] = 27,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[9] = {
		.scroll_line = 100,
		.weapon = EW_GUN,
		.x = -14,
		.y = 19,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 7,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 34,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 50,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 6,
			[1] = 28,
			[2] = 50,
			[3] = 0,
			[4] = 0,
		},
	},
	[10] = {
		.scroll_line = 108,
		.weapon = EW_GUN,
		.x = -14,
		.y = 18,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 7,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 27,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 48,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 6,
			[1] = 27,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[11] = {
		.scroll_line = 123,
		.weapon = EW_GUN,
		.x = 47,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 17,
			[1] = 62,
			[2] = 82,
			[3] = 0,
			[4] = 0,
		},
	},
	[12] = {
		.scroll_line = 129,
		.weapon = EW_GUN,
		.x = 84,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 19,
			[1] = 64,
			[2] = 86,
			[3] = 0,
			[4] = 0,
		},
	},
	[13] = {
		.scroll_line = 131,
		.weapon = EW_GUN,
		.x = 128,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 22,
			[1] = 66,
			[2] = 86,
			[3] = 0,
			[4] = 0,
		},
	},
	[14] = {
		.scroll_line = 135,
		.weapon = EW_GUN,
		.x = 64,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 23,
			[1] = 68,
			[2] = 85,
			[3] = 0,
			[4] = 0,
		},
	},
	[15] = {
		.scroll_line = 136,
		.weapon = EW_GUN,
		.x = 96,
		.y = -20,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 23,
			[1] = 68,
			[2] = 85,
			[3] = 0,
			[4] = 0,
		},
	},
	[16] = {
		.scroll_line = 144,
		.weapon = EW_GUN,
		.x = 48,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 22,
			[1] = 64,
			[2] = 85,
			[3] = 0,
			[4] = 0,
		},
	},
	[17] = {
		.scroll_line = 145,
		.weapon = EW_GUN,
		.x = 88,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 22,
			[1] = 64,
			[2] = 85,
			[3] = 0,
			[4] = 0,
		},
	},
	[18] = {
		.scroll_line = 146,
		.weapon = EW_GUN,
		.x = 128,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 22,
			[1] = 64,
			[2] = 85,
			[3] = 0,
			[4] = 0,
		},
	},
	[19] = {
		.scroll_line = 151,
		.weapon = EW_GUN,
		.x = -14,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 26,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 26,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[20] = {
		.scroll_line = 152,
		.weapon = EW_GUN,
		.x = 190,
		.y = 0,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 26,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 26,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[21] = {
		.scroll_line = 160,
		.weapon = EW_GUN,
		.x = -14,
		.y = 2,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 26,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 26,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
	[22] = {
		.scroll_line = 181,
		.weapon = EW_GUN,
		.x = 190,
		.y = 22,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_WSW,
				.start_step = 15,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_W,
				.start_step = 26,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 15,
			[1] = 26,
			[2] = 48,
			[3] = 0,
			[4] = 0,
		},
	},
};

static const struct enemy_spawn SPAWN_ENTRY(6)[] = {
	[0] = {
		.scroll_line = 6,
		.weapon = EW_GUN,
		.x = 88,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 21,
			[1] = 64,
			[2] = 84,
			[3] = 0,
			[4] = 0,
		},
	},
	[1] = {
		.scroll_line = 7,
		.weapon = EW_GUN,
		.x = 128,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 21,
			[1] = 64,
			[2] = 84,
			[3] = 0,
			[4] = 0,
		},
	},
	[2] = {
		.scroll_line = 19,
		.weapon = EW_GUN,
		.x = 96,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 21,
			[1] = 64,
			[2] = 84,
			[3] = 0,
			[4] = 0,
		},
	},
	[3] = {
		.scroll_line = 28,
		.weapon = EW_GUN,
		.x = 88,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 21,
			[1] = 64,
			[2] = 84,
			[3] = 0,
			[4] = 0,
		},
	},
	[4] = {
		.scroll_line = 28,
		.weapon = EW_GUN,
		.x = 128,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 21,
			[1] = 64,
			[2] = 84,
			[3] = 0,
			[4] = 0,
		},
	},
	[5] = {
		.scroll_line = 35,
		.weapon = EW_GUN,
		.x = 88,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 21,
			[1] = 64,
			[2] = 84,
			[3] = 0,
			[4] = 0,
		},
	},
	[6] = {
		.scroll_line = 46,
		.weapon = EW_GUN,
		.x = 96,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 21,
			[1] = 64,
			[2] = 84,
			[3] = 0,
			[4] = 0,
		},
	},
	[7] = {
		.scroll_line = 56,
		.weapon = EW_GUN,
		.x = 88,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 21,
			[1] = 64,
			[2] = 84,
			[3] = 0,
			[4] = 0,
		},
	},
	[8] = {
		.scroll_line = 64,
		.weapon = EW_GUN,
		.x = 128,
		.y = -21,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 0,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 21,
			[1] = 64,
			[2] = 84,
			[3] = 0,
			[4] = 0,
		},
	},
};

static const struct enemy_spawn SPAWN_ENTRY(7)[] = {
	[0] = {
		.scroll_line = 9,
		.weapon = EW_GUN,
		.x = -14,
		.y = 95,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 19,
			[1] = 30,
			[2] = 41,
			[3] = 52,
			[4] = 0,
		},
	},
	[1] = {
		.scroll_line = 18,
		.weapon = EW_GUN,
		.x = -14,
		.y = 16,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 7,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_OSO,
				.start_step = 16,
				.vel = 7,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 25,
				.vel = 7,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_ONO,
				.start_step = 36,
				.vel = 7,
			},
			[4] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 45,
				.vel = 7,
			},
		},
		.shots = {
			[0] = 14,
			[1] = 23,
			[2] = 36,
			[3] = 44,
			[4] = 0,
		},
	},
	[2] = {
		.scroll_line = 30,
		.weapon = EW_GUN,
		.x = -15,
		.y = 137,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER2_RIGHT,
				.dir = DIR16_OSO,
				.start_step = 10,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 19,
			[1] = 38,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[3] = {
		.scroll_line = 66,
		.weapon = EW_GUN,
		.x = -14,
		.y = 114,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 6,
			},
			[1] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_SO,
				.start_step = 18,
				.vel = 6,
			},
			[2] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_O,
				.start_step = 32,
				.vel = 6,
			},
			[3] = {
				.shape = ES_SOLDIER1_RIGHT,
				.dir = DIR16_OSO,
				.start_step = 49,
				.vel = 6,
			},
		},
		.shots = {
			[0] = 18,
			[1] = 32,
			[2] = 49,
			[3] = 0,
			[4] = 0,
		},
	},
	[4] = {
		.scroll_line = 84,
		.weapon = EW_GUN,
		.x = -14,
		.y = 16,
		.route = {
			[0] = {
				.shape = ES_SOLDIER2_RIGHT,
				.dir = DIR16_OSO,
				.start_step = 0,
				.vel = 9,
			},
		},
		.shots = {
			[0] = 14,
			[1] = 28,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[5] = {
		.scroll_line = 105,
		.weapon = EW_GUN,
		.x = -14,
		.y = 95,
		.route = {
			[0] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 0,
				.vel = 3,
			},
			[1] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 28,
				.vel = 3,
			},
			[2] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 39,
				.vel = 3,
			},
			[3] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 48,
				.vel = 3,
			},
			[4] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 59,
				.vel = 3,
			},
			[5] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 70,
				.vel = 3,
			},
			[6] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_O,
				.start_step = 79,
				.vel = 3,
			},
			[7] = {
				.shape = ES_SOLDIER1_DOWN,
				.dir = DIR16_S,
				.start_step = 90,
				.vel = 3,
			},
		},
		.shots = {
			[0] = 28,
			[1] = 39,
			[2] = 48,
			[3] = 59,
			[4] = 70,
			[5] = 79,
			[6] = 90,
			[7] = 0,
		},
	},
};

const struct enemy_spawn_screen SPAWN_MAP[NUM_SCREENS] = {
	[7] = {
		.num_spawns = 6,
		.spawns = SPAWN_ENTRY(7),
	},
	[6] = {
		.num_spawns = 9,
		.spawns = SPAWN_ENTRY(6),
	},
	[5] = {
		.num_spawns = 23,
		.spawns = SPAWN_ENTRY(5),
	},
	[4] = {
		.num_spawns = 18,
		.spawns = SPAWN_ENTRY(4),
	},
	[3] = {
		.num_spawns = 20,
		.spawns = SPAWN_ENTRY(3),
	},
	[2] = {
		.num_spawns = 20,
		.spawns = SPAWN_ENTRY(2),
	},
	[1] = {
		.num_spawns = 8,
		.spawns = SPAWN_ENTRY(1),
	},
	[0] = {
		.num_spawns = 0,
		.spawns = 0,
	},
};

#undef MAP_NAME
